-- ============================================================================
-- vocabulary_v7_phase1_dictionary.sql
--
-- Source:       SeedCorpus/INGEST_VOCABULARY_DESIGN.md — v7 (2026-08-21,
--               monorepo 43b09fc), §11.1–§11.4, §11.8 Phase 1; rulings OR-11,
--               OR-12, OR-17.
-- Author date:  2026-08-21
-- Scope:        ADI group ONLY (`ADI_DATABASE_URL`, binding `adiSql`) — the
--               dictionary's home. Three steps, one transaction:
--                 P1.1 — `vocabulary_dictionary_version`: the monotonic
--                        dictionary version counter (§11.2), initialized to 1
--                        (this file's seed IS the version-1 curation act).
--                 P1.2 — `vocabulary_terms.phi_default` column (nullable
--                        BOOLEAN): the §11.2 snapshot's per-term "PHI default"
--                        field gains its schema home. NO values are set here —
--                        populating it is a curation decision left entirely to
--                        the owner.
--                 P1.3 — seed the eight remaining closed vocabularies (97
--                        terms) so the dictionary carries every namespace the
--                        misfire census validates, letting the Worker in-code
--                        sets demote to bootstrap fallback (§11.4, copy ledger
--                        §11.6 item 2).
--
--               NOT in scope: any user-flow / seed / KT database (nothing
--               here touches them); the snapshot itself (generated by the
--               Worker / published to KV, never stored in Neon — §11.3).
--
-- ── AUTHORING DECISIONS (design delegates these; flagged for owner review) ───
--   P1-A. THE SEED CONTENT IS THE IN-CODE SETS, VERBATIM. §11.6 retires the
--         Worker's in-code copies to bootstrap fallback "by Phase 1", which
--         requires the dictionary to carry all nine census namespaces, not
--         just rh.atom.kind. The 97 terms below are byte-identical to the
--         sets in src/ingest-vocab.mjs (generated from the module, not
--         hand-typed) — the same owner-adopted-canonical framing as the v6
--         baseline's 33-kind seed. This is a CURATION ACT recorded as SQL,
--         exactly like that baseline seed; nothing here is extractor-authored,
--         and OR-12 stands untouched.
--   P1-B. The provider-role subtype hole is NOT seeded. Provider atoms carry
--         free-text roles as subtypes (owner ruling 2026-08-21: expected
--         output, exempt from the census via skipWhen) — those are open
--         vocabulary by construction and never become terms here.
--   P1-C. The counter is a singleton row, bumped by the Worker's publish
--         route via UPDATE .. RETURNING. It is machinery, not vocabulary:
--         OR-12 governs `vocabulary_terms` authorship and does not reach it.
--         Initialized to 1, not 0: the version-1 snapshot published right
--         after this migration is the snapshot OF this file's curation act.
--   P1-D. `phi_default` is nullable with no default and no CHECK. NULL means
--         "no PHI default declared for this term" — an honest absence, not
--         false. The snapshot carries it as-is.
--
-- ── HOW TO RUN ──────────────────────────────────────────────────────────────
-- 1. ADI group only. Runs TWICE: ADI staging first, verify, then ADI
--    production (DATABASE_LAYOUT.md § Migration workflow rules, rule 4).
-- 2. The `DO $$ ... $$` endpoint guard rail (rule 6): EDIT the
--    `expected_endpoint` literal before each run.
-- 3. If run programmatically instead of the browser editor, the runner must
--    be a real Postgres client executing whole statements in one transaction —
--    never a `split(";")` splitter (rule 5). The dollar-quoted guard block
--    would be shredded by naive splitting.
-- 4. Ends with the `schema_migrations` ledger insert (rule 3) and a trailing
--    verify block for an independent reconnect (rule 7).
--
-- NON-DESTRUCTIVE THROUGHOUT: no wipe, no drop, no row rewrite. Everything is
-- CREATE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS / INSERT ON CONFLICT DO
-- NOTHING, so a re-run is a no-op.
-- ============================================================================

BEGIN;

-- Endpoint guard rail — DATABASE_LAYOUT.md § Migration workflow rules, rule 6.
-- EDIT `expected_endpoint` for the target you are running against RIGHT NOW.
DO $guard$
DECLARE
  expected_endpoint TEXT := 'ep-long-silence-ampu7eor';  -- <<< EDIT: ADI staging
  -- expected_endpoint TEXT := 'ep-quiet-union-amsm4lqz';  -- ADI production
  actual_endpoint   TEXT;
BEGIN
  actual_endpoint := current_setting('neon.endpoint_id', true);
  IF actual_endpoint IS DISTINCT FROM expected_endpoint THEN
    RAISE EXCEPTION
      'ENDPOINT GUARD: expected %, connected to %. Aborting.',
      expected_endpoint, COALESCE(actual_endpoint, '<null>');
  END IF;
END
$guard$;


-- ===========================================================================
-- ==  P1.1 — THE VERSION COUNTER:  vocabulary_dictionary_version           ==
-- ==  §11.2: "on every curation act the dictionary's version increments    ==
-- ==  (monotonic integer)"                                                 ==
-- ===========================================================================
--
-- Singleton row; the Worker's snapshot-publish route bumps it atomically
-- (UPDATE .. RETURNING) exactly when published dictionary content actually
-- changed. Machinery, not vocabulary: OR-12's authorship rule governs
-- `vocabulary_terms` and does not reach this table. Lives beside the
-- dictionary so the whole promotion loop stays inside the ADI group (§11.3
-- rejected the user-flow home for exactly the cross-group-write reason).

CREATE TABLE IF NOT EXISTS vocabulary_dictionary_version (
  singleton   BOOLEAN PRIMARY KEY DEFAULT TRUE
              CONSTRAINT vocabulary_dictionary_version_singleton_check
              CHECK (singleton),
  version     BIGINT NOT NULL DEFAULT 0
              CONSTRAINT vocabulary_dictionary_version_nonnegative_check
              CHECK (version >= 0),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Initialized to 1 (authoring decision P1-C): this file's seed is the
-- version-1 curation act, and the first published snapshot is version 1.
INSERT INTO vocabulary_dictionary_version (singleton, version)
VALUES (TRUE, 1)
ON CONFLICT (singleton) DO NOTHING;

COMMENT ON TABLE vocabulary_dictionary_version IS
  'Monotonic dictionary version counter (INGEST_VOCABULARY_DESIGN v7 §11.2). '
  'Singleton row, bumped by the Worker snapshot publish '
  '(POST /v1/admin/vocabulary/snapshot) when published content changed. '
  'Machinery, not vocabulary — OR-12 governs vocabulary_terms, not this.';


-- ===========================================================================
-- ==  P1.2 — THE PHI-DEFAULT COLUMN:  vocabulary_terms.phi_default         ==
-- ==  §11.2's snapshot term shape names a per-term "PHI default"           ==
-- ===========================================================================
--
-- Nullable, no default, no values set by this file (authoring decision P1-D):
-- the column is the schema home §11.2's snapshot field needs; its content is
-- the owner's curation. Adding a column is a schema change, not term
-- authorship — OR-12 untouched.

ALTER TABLE vocabulary_terms ADD COLUMN IF NOT EXISTS phi_default BOOLEAN;

COMMENT ON COLUMN vocabulary_terms.phi_default IS
  'Per-term PHI default carried into the snapshot (v7 §11.2). NULL = no '
  'default declared (honest absence, not false). Curation metadata; never '
  'set by code.';


-- ===========================================================================
-- ==  P1.3 — SEED THE REMAINING CLOSED VOCABULARIES (97 terms)             ==
-- ==  §11.4 / §11.6: the census validates against the snapshot; the        ==
-- ==  in-code sets demote to bootstrap fallback                            ==
-- ===========================================================================
--
-- CURATION ACT RECORDED AS SQL (authoring decision P1-A) — same posture as
-- the v6 baseline's 33-kind seed: owner-adopted canonical terms, generated
-- byte-identical from src/ingest-vocab.mjs (the previously-authoritative
-- in-code copies these rows retire to fallback). Namespaces follow §5.3's
-- illustrative scheme exactly as src/vocabulary-misfire.mjs's NAMESPACE
-- constants record it — the census's field-position → namespace mapping and
-- these rows must agree, or every atom would misfire.
--
-- The two deliberately-divergent subtype spellings (prompt "name"/"address"
-- vs adapter "patientName"/"street") are BOTH seeded — both arms' output is
-- known vocabulary, per the in-code set's own documentation.

INSERT INTO vocabulary_terms (namespace, code, created_by) VALUES
  -- rh.atom.subtype (41 terms)
  ('rh.atom.subtype', 'name',                  'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'dateOfBirth',           'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'sex',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'sexAssignedAtBirth',    'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'genderIdentity',        'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'bloodType',             'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'pronouns',              'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'age',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'race',                  'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'ethnicity',             'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'mrn',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'ssn',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'ssnLastFour',           'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'billingAccountNumber',  'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'memberNumber',          'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'subscriberNumber',      'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'encounterNumber',       'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'unspecifiedIdentifier', 'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'phone',                 'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'email',                 'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'fax',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'unspecifiedContact',    'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'relationship',          'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'address',               'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'npi',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'role',                  'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'specialty',             'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'credentials',           'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'facilityName',          'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'departmentName',        'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'accessionNumber',       'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'orderNumber',           'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'formCode',              'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'documentType',          'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'barcode',               'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'patientName',           'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'street',                'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'city',                  'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'state',                 'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'zip',                   'vocabulary-v7-phase1'),
  ('rh.atom.subtype', 'facility',              'vocabulary-v7-phase1'),
  -- rh.column-role (5 terms)
  ('rh.column-role', 'analyte_name',          'vocabulary-v7-phase1'),
  ('rh.column-role', 'value',                 'vocabulary-v7-phase1'),
  ('rh.column-role', 'units',                 'vocabulary-v7-phase1'),
  ('rh.column-role', 'reference_range',       'vocabulary-v7-phase1'),
  ('rh.column-role', 'flag',                  'vocabulary-v7-phase1'),
  -- rh.certainty (3 terms)
  ('rh.certainty', 'specific',              'vocabulary-v7-phase1'),
  ('rh.certainty', 'parent_only',           'vocabulary-v7-phase1'),
  ('rh.certainty', 'low_confidence',        'vocabulary-v7-phase1'),
  -- rh.phi.type (32 terms)
  ('rh.phi.type', 'mrn',                   'vocabulary-v7-phase1'),
  ('rh.phi.type', 'ssn',                   'vocabulary-v7-phase1'),
  ('rh.phi.type', 'ssnLastFour',           'vocabulary-v7-phase1'),
  ('rh.phi.type', 'accountNumber',         'vocabulary-v7-phase1'),
  ('rh.phi.type', 'accessionNumber',       'vocabulary-v7-phase1'),
  ('rh.phi.type', 'licenseNumber',         'vocabulary-v7-phase1'),
  ('rh.phi.type', 'deviceIdentifier',      'vocabulary-v7-phase1'),
  ('rh.phi.type', 'memberNumber',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'patientName',           'vocabulary-v7-phase1'),
  ('rh.phi.type', 'providerName',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'guardianName',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'emergencyContactName',  'vocabulary-v7-phase1'),
  ('rh.phi.type', 'staffName',             'vocabulary-v7-phase1'),
  ('rh.phi.type', 'patientAddress',        'vocabulary-v7-phase1'),
  ('rh.phi.type', 'patientPhone',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'patientEmail',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'providerPhone',         'vocabulary-v7-phase1'),
  ('rh.phi.type', 'providerFax',           'vocabulary-v7-phase1'),
  ('rh.phi.type', 'providerAddress',       'vocabulary-v7-phase1'),
  ('rh.phi.type', 'facilityName',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'facilityAddress',       'vocabulary-v7-phase1'),
  ('rh.phi.type', 'dob',                   'vocabulary-v7-phase1'),
  ('rh.phi.type', 'dateOfService',         'vocabulary-v7-phase1'),
  ('rh.phi.type', 'dateOfReport',          'vocabulary-v7-phase1'),
  ('rh.phi.type', 'dateOfAdmission',       'vocabulary-v7-phase1'),
  ('rh.phi.type', 'dateOfDischarge',       'vocabulary-v7-phase1'),
  ('rh.phi.type', 'dateSigned',            'vocabulary-v7-phase1'),
  ('rh.phi.type', 'urlOrHandle',           'vocabulary-v7-phase1'),
  ('rh.phi.type', 'ipAddress',             'vocabulary-v7-phase1'),
  ('rh.phi.type', 'photograph',            'vocabulary-v7-phase1'),
  ('rh.phi.type', 'biometric',             'vocabulary-v7-phase1'),
  ('rh.phi.type', 'otherIdentifier',       'vocabulary-v7-phase1'),
  -- rh.atom.date-role (8 terms)
  ('rh.atom.date-role', 'collection',            'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'study',                 'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'admission',             'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'discharge',             'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'service',               'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'visit',                 'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'report',                'vocabulary-v7-phase1'),
  ('rh.atom.date-role', 'narrativeReference',    'vocabulary-v7-phase1'),
  -- rh.reliability (3 terms)
  ('rh.reliability', 'high',                  'vocabulary-v7-phase1'),
  ('rh.reliability', 'medium',                'vocabulary-v7-phase1'),
  ('rh.reliability', 'low',                   'vocabulary-v7-phase1'),
  -- rh.edge.kind (2 terms)
  ('rh.edge.kind', 'belongs_to_panel',      'vocabulary-v7-phase1'),
  ('rh.edge.kind', 'belongs_to_address',    'vocabulary-v7-phase1'),
  -- rh.edge.source (3 terms)
  ('rh.edge.source', 'llama_extract',         'vocabulary-v7-phase1'),
  ('rh.edge.source', 'walker',                'vocabulary-v7-phase1'),
  ('rh.edge.source', 'reviewer',              'vocabulary-v7-phase1')
ON CONFLICT (namespace, code) DO NOTHING;


-- Ledger — DATABASE_LAYOUT.md § Migration workflow rules, rule 3.
INSERT INTO schema_migrations (filename, applied_by)
VALUES ('vocabulary_v7_phase1_dictionary.sql', 'vocabulary-v7-phase1')
ON CONFLICT (filename) DO NOTHING;

COMMIT;


-- ── Verify (run after COMMIT, on an independent reconnect) ──────────────────
-- DATABASE_LAYOUT.md § Migration workflow rules, rule 7.
--
-- -- Counter exists, version 1.
-- SELECT singleton, version, updated_at FROM vocabulary_dictionary_version;
--
-- -- Nine namespaces, 130 terms total (33 kind + 97 seeded here), 2 retired.
-- SELECT namespace, count(*), count(retired_at) AS retired
-- FROM vocabulary_terms GROUP BY namespace ORDER BY namespace;
-- -- Expect: rh.atom.date-role 8 / rh.atom.kind 33 (2 retired) /
-- --         rh.atom.subtype 41 / rh.certainty 3 / rh.column-role 5 /
-- --         rh.edge.kind 2 / rh.edge.source 3 / rh.phi.type 32 /
-- --         rh.reliability 3
--
-- -- phi_default column present, nullable boolean, no default, all NULL.
-- SELECT column_name, data_type, is_nullable, column_default
-- FROM information_schema.columns
-- WHERE table_name = 'vocabulary_terms' AND column_name = 'phi_default';
-- SELECT count(*) FROM vocabulary_terms WHERE phi_default IS NOT NULL; -- 0
--
-- SELECT filename, applied_at, applied_by FROM schema_migrations
-- WHERE filename = 'vocabulary_v7_phase1_dictionary.sql';


-- ── Rollback ────────────────────────────────────────────────────────────────
-- Fully reversible (nothing here is a wipe or a rewrite). Rolling back the
-- seed deletes only rows this file authored (created_by scoped) that no atom
-- references; a referenced term's FK will refuse the delete loudly, which is
-- correct (retire it instead).
--
-- BEGIN;
-- DELETE FROM vocabulary_terms WHERE created_by = 'vocabulary-v7-phase1';
-- ALTER TABLE vocabulary_terms DROP COLUMN IF EXISTS phi_default;
-- DROP TABLE IF EXISTS vocabulary_dictionary_version;
-- DELETE FROM schema_migrations
-- WHERE filename = 'vocabulary_v7_phase1_dictionary.sql';
-- COMMIT;
